services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    command: postgres -p ${POSTGRES_PORT}
    env_file:
      - .env
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - ecommerce_wine

  node:
    container_name: node
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - ecommerce_wine

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - node-volume:/var/www/html
    depends_on:
      - postgres
      - node
    networks:
      - ecommerce_wine


networks:
  ecommerce_wine:
    driver: bridge
    
volumes:
  postgres-volume:
  node-volume: